### ISSUE TITLE
Feature Request: Search Directories

### ISSUE THREAD

**Issue by vknabel** [JohnSundell/Marathon#1]
Hey thanks for open sourcing your project!

I wanted to ask for a mechanism to make Marathon additionally search in different paths like `~/scripts/` or `$PROJECT_ROOT/Scripts`. 

Some use cases are:
- In SwiftPM projects: SwiftPM doesn't like other Swift files in project root except Package.swift
- User Level Scripts: creating a very specific kind of projects

My ideas would be:
- recursively search in parent folders
- put it into Marathonfile, which would break its format
- search in some hard-coded folders like `marathon` or `scripts`

**Comment by JohnSundell** [comment]
Hi @vknabel! Unsure what you mean by that Marathon should "search". You just give the path to your script when running it like `$ marathon run ~/scripts/myScript.swift`. Would you mind clarifying what you mean? 🙂

**Comment by vknabel** [comment]
@JohnSundell sorry for the strange issue description. 😅

Essentially it's just about convenience. I thought about omitting the path for running the script in certain cases.
Marathon would then test some specific paths, looking for the provided script name. 

I attached an example where Marathon would "search" for a script with the given name. 
The first script, that exists will be executed. 
```
$ marathon run myScript
# ./myScript.swift doesn't exist, trying next
# ./scripts/myScript.swift doesn't exist, trying next
# ~/scripts/myScript.swift, found
# Running ~/scripts/myScript.swift
> Hello World
```

Of course one could simply run `$ marathon run ~/scripts/myScript.swift`, but I think a more "intelligent" behavior would be great. Especially for SwiftPM users as they would always need run `$ marathon run scripts/myScript.swift`.

**Comment by JohnSundell** [comment]
Ah, now I understand what you mean - thanks 😄 

Honestly, I think adding functionality like this would make Marathon more complicated than it has to be. In order to achieve this kind of global availability, I'd just create an alias for `marathon run path/to/my/script` and execute the aliased command from anywhere.

**Comment by vknabel** [comment]
@JohnSundell I understand your reasoning.

An alias should be sufficient. Thanks for your honest feedback and suggestion. 👌

**Comment by JohnSundell** [comment]
@vknabel Anytime 😄 Keep the suggestions and feedback coming - it's super valuable! 👍

**Comment by vknabel** [comment]
I wanted to share my solution to this issue, although it will probably be far too complex for most use cases. Usually a simple `alias myScript = 'marathon run ~/path/to/myScript'` should be fine.

My solution is a Marathon script located [here](https://gist.github.com/vknabel/64c81bae35dd997d1fe1da9705f7afee), which must be configured by an alias and two environment variables. 
It has some downsides: Marathon needs to compile two scripts instead of one.
As said usually the best way is to simply define you some alias.
