### ISSUE TITLE
marathon add not resolving / finding Package.swift

### ISSUE THREAD

**Issue by mathieutozer** [JohnSundell/Marathon#103]
When doing the following 
marathon add https://github.com/kareman/SwiftShell
marathon add https://github.com/kylef/PathKit

I get 

💥  Could not resolve the name of package at 'https://github.com/kylef/PathKit'
👉  Make sure that the package you're trying to add is reachable, and has a Package.swift file

Both are reachable and have Package.swift in their root directories - is there possibly some other thing making them incompatible that isn't being shown in the error message?

**Comment by JohnSundell** [comment]
@mathieutozer Hi, and welcome to Marathon 👋 You need to give the `add` command a *Git URL* to add. So in this case, simply append `.git` to the URLs that you want to add and it'll work. We can definetly improve the error message Marathon displays to give you better information on why adding these packages failed 👍

**Comment by mathieutozer** [comment]
That worked, but for SwiftShell's case I am now getting 

marathon add http://github.com/mathieutozer/SwiftShell.git
🏃  Cloning http://github.com/mathieutozer/SwiftShell.git...
   Resolving latest major version for http://github.com/mathieutozer/SwiftShell.git...
💥  Could not resolve the latest version for package at 'http://github.com/mathieutozer/SwiftShell.git'
👉  Make sure that the package you're trying to add is reachable, and has at least one tagged release

It looks like the project does have tagged releases https://github.com/kareman/SwiftShell/tags

**Comment by JohnSundell** [comment]
@mathieutozer You are missing an "s" in "https" in your URL 🙂 Use this command and it will work:
```
marathon add https://github.com/mathieutozer/SwiftShell.git
```

**Comment by mathieutozer** [comment]
oops ☺️

**Comment by JohnSundell** [comment]
@mathieutozer 😄 Cool if I close this?
