### ISSUE TITLE
Replace options syntax

### ISSUE THREAD

**Issue by pixyzehn** [JohnSundell/Marathon#12]
Personally, to use `--no-open` instead of `-no-open` looks natural like other CLI tools. What do you think of that?
If you think so, I'd like to replace.

**Comment by JohnSundell** [comment]
@pixyzehn Yeah, that seems like a good idea, feel free to make that change 👍

**Comment by pixyzehn** [comment]
@JohnSundell Glad to hear that 👍  I'll submit a PR.

**Comment by JohnSundell** [comment]
Implemented by @pixyzehn in https://github.com/JohnSundell/Marathon/pull/15
