### ISSUE TITLE
Adding --verbose changes the paths of the installed projects

### ISSUE THREAD

**Issue by orta** [JohnSundell/Marathon#128]
<img width="855" alt="screen shot 2017-09-08 at 10 00 43" src="https://user-images.githubusercontent.com/49038/30215069-abddc00c-947c-11e7-9209-6dae4d39e39a.png">

**Comment by orta** [comment]
I'm assuming this is a re-name script feature, that ideally should strip `--verbose` from an array of args

**Comment by JohnSundell** [comment]
Yeah we should totally fix this 👍

**Comment by johandk89** [comment]
I created a pull request for this: https://github.com/JohnSundell/Marathon/pull/131
