### ISSUE TITLE
Give suggestion to add a package if that's what fails script compilation

### ISSUE THREAD

**Issue by JohnSundell** [JohnSundell/Marathon#13]
If a script fails to compile because of a missing package, it would be nice to suggest to the user that they run `marathon add <package-url>` to add it. Right now, this is the output you get:

```
💥  Failed to compile script
👉  The following error(s) occured:
     - 2:8: no such module 'Files'
```

It would be nice if, in addition to the above, the following information was included:

```
👉  You can add Files to Marathon using 'marathon add <url-to-Files>'
```

**Comment by pixyzehn** [comment]
@JohnSundell 
Could you close this issue? :)

**Comment by JohnSundell** [comment]
@pixyzehn I sure can! Thanks for the reminder 😅
