### ISSUE TITLE
build warning

### ISSUE THREAD

**Issue by MasterSwift** [JohnSundell/Marathon#132]
warning: '--chdir/-C' option is deprecated; use '--package-path' instead 

have you seen this error ? For some reason, its causing marathon to output 
💥  Failed to compile script

but it only happens on a linux server I'm using. on a local macOS computer, I get no errors and it builds perfectly. not sure if this is causing the error or something else not being outputted into the CL.

**Comment by orta** [comment]
This could be that one version is using Swift 3, and the other is using Swift 4: type `swift package --version` to see which version is on your setup.

**Comment by MasterSwift** [comment]
it was on swift 3 . I don't have admin rights but somehow with swiftenv (https://github.com/kylef/swiftenv) , i updated it to swift 4. probably thats where the issue is coming

**Comment by orta** [comment]
Yeah, that will be it.

**Comment by MasterSwift** [comment]
updated to swift 4 
 
warning: '--chdir/-C' option is deprecated; use '--package-path' instead
   error: product dependency 'cURL' not found
💥  Failed to compile script
