### ISSUE TITLE
Failed to compile script

### ISSUE THREAD

**Issue by UncleRic** [JohnSundell/Marathon#157]
I followed the example thusly:

$:swift --version
Apple Swift version 4.0.3 (swiftlang-900.0.74.1 clang-900.0.39.2)
Target: x86_64-apple-macosx10.9

$:marathon create helloWorld "import Foundation; print(\"Hello world\")"
💥  Failed to open script 'helloWorld' for editing
👉  Make sure that it exists and that its file is readable

$:ls helloWorld.*
helloWorld.swift

$: marathon run helloWorld
💥  Failed to compile script
$:

$:cat helloWorld.swift
import Foundation; print("Hello world")
$:

**Comment by gunesmert** [comment]
Same here, it is not possible to compile example script. @JohnSundell

**Comment by proxpero** [comment]
I encountered this issue as well. The fix for me was to install using SPM not homebrew. I think the homebrew version is stale. (I also deleted my .marathon folder—but I don't know if that's relevant)

**Comment by bduisenov** [comment]
+1

**Comment by narner** [comment]
+1, also experiencing the same issue after using brew

**Comment by JohnSundell** [comment]
Hey guys, sorry, a bit late to the party here 😅 It's correct that the latest version of Marathon is not yet available on Homebrew (see https://github.com/JohnSundell/Marathon/issues/145 for details). I hope to make it available there soon, but in the meantime you can use `master` (by installing through SPM or Mint) which contains a fix for Xcode 9.1 and later 👍

**Comment by mkkroliks** [comment]
I've installed marathon via brew but after reading comments about issue I uninstalled it and used make/SPM but still encounter the same problem. 

`marathon create helloWorld "import Foundation; print(\"Hello world\")"
🐣  Created script at helloWorld.swift
💥  Failed to open script 'helloWorld' for editing
👉  Make sure that it exists and that its file is readable`

Any suggestions? I could not find any `.marathon` folder. Where is it located?

**Comment by proxpero** [comment]
Files with a dot in front are hidden. You can google "show hidden files mac" to find out how to reveal them in Finder. My `.marathon` file is in my home folder. So from the Finder.app menu: Go -> Go to Folder…  and enter `~/.marathon`. (`~` means your home folder)

**Comment by mkkroliks** [comment]
@proxpero Cool thanks a lot. I was looking for this folder in brew directory and did not know it can appear in home directory. It solved my issue.

**Comment by lf-araujo** [comment]
Can confirm the similar (same?) bug on linux. Marathon is not usable in my installation at the moment, unfortunately.

```
└─λ swift --version
Swift version 4.0.3 (swift-4.0.3-RELEASE)
Target: x86_64-unknown-linux-gnu
```

Marathon was installed using clone and swift build.


If I try to run the Files example from the Readme.md with the --verbose flag I get:

```
   /home/luis/.marathon/Scripts/Cache/-tmp-Selenops-teste/.build/checkouts/Files.git--6062313482316197225/Sources/Files.swift:1024:12: error: value of type 'ObjCBool' (aka 'Bool') has no member 'boolValue'
           if objCBool.boolValue {
              ^~~~~~~~ ~~~~~~~~~
   warning: '--chdir/-C' option is deprecated; use '--package-path' instead
```

By the looks it may be a distinct problem, related to latest Files dependency.

**Comment by rob-nash** [comment]
You will need to do exactly what it says in the README

```swift
marathon create helloWorld "import Foundation; print(\"Hello world\")"
```
Your script will build fine if you escape the quote marks.

**Comment by lf-araujo** [comment]
This issue is no more, someone should close it.
