### ISSUE TITLE
Install command with Mint

### ISSUE THREAD

**Issue by fassko** [JohnSundell/Marathon#163]
Right now using Mint install command is

    $ mint run JohnSundell/Marathon

Shouldn't it be **install** instead of **run**?

    $ mint install JohnSundell/Marathon

**Comment by JohnSundell** [comment]
@yonaskolb Which one is the correct one? 🙂 (IIRC `run` does `install` if needed)

**Comment by yonaskolb** [comment]
Either is fine. As @JohnSundell says`run` will also install.
Now that Mint supports global installs I’ve updated the documentation to give `install` examples to match the other installation methods

**Comment by fassko** [comment]
I think install does make sense more as it actually installs. Thanks!
