### ISSUE TITLE
Write premissions

### ISSUE THREAD

**Issue by MillerApps** [JohnSundell/Marathon#165]
![screen shot 2018-04-06 at 5 03 46 am](https://user-images.githubusercontent.com/3836934/38412745-0783defc-3958-11e8-8373-58b18ea9cd4e.png)
Ended up installing manually😭 

Also posted this issue [here](https://github.com/JohnSundell/XcodeTheme/issues/5) as well.

**Comment by IgorMuzyka** [comment]
Same problem, manuall installation does not help

**Comment by rob-nash** [comment]
are you using

```
Apple Swift version 4.1 (swiftlang-902.0.48 clang-902.0.37.1)
```

if you append

```
--verbose
```

do you get

```
error: unknown option --enable-prefetching; use --help to list available options
```

**Comment by rob-nash** [comment]
If so, same issue as 

[#151](https://github.com/JohnSundell/Marathon/issues/151)

**Comment by MillerApps** [comment]
@rob-nash Yes, its the same issue.

**Comment by mkkroliks** [comment]
Updating marathon to 3.0.0 fixed the issue.
