### ISSUE TITLE
Duplicated file path

### ISSUE THREAD

**Issue by pixyzehn** [JohnSundell/Marathon#21]
I think the problem is that the path included a redundant `/` when creating like `/Users/pixyzehn/Developer//hoge.swift`.
Is that issue in `Files` ?

```
 pixyzehn ⮀ ~/Developer ⮀ marathon create hoge
🐣  Created script at hoge.swift
✏️  Opening Hoge.xcodeproj/

ℹ️  Marathon will keep running, in order to commit any changes you make in Xcode back to the original script file
   Press any key once you're done

 pixyzehn ⮀ ~/Developer ⮀ marathon list
📄  Scripts
----------
/Users/pixyzehn/Developer//hoge.swift

👉  To remove either a package or the cached data for a script, use 'marathon remove'
 pixyzehn ⮀ ~/Developer ⮀ marathon run hoge
 pixyzehn ⮀ ~/Developer ⮀ marathon list
📄  Scripts
----------
/Users/pixyzehn/Developer//hoge.swift
/Users/pixyzehn/Developer/hoge.swift

👉  To remove either a package or the cached data for a script, use 'marathon remove'
```

**Comment by JohnSundell** [comment]
Good find @pixyzehn! It might be an issue with Files, or with how Marathon processes the paths, I'll start by seeing if I can reproduce the problem in a Files test case, and we can take it from there 😄

**Comment by pixyzehn** [comment]
@JohnSundell 
As I found the cause of bug, I fixed:)
Please check my PR in Files https://github.com/JohnSundell/Files/pull/8

**Comment by JohnSundell** [comment]
Thanks @pixyzehn! Really appreciate your help on this 👍

**Comment by JohnSundell** [comment]
Will make a new release of Files now so that Marathon can take advantage of the fix.

**Comment by pixyzehn** [comment]
Thanks! Looking forward to it!
