### ISSUE TITLE
marathon uninstall command?

### ISSUE THREAD

**Issue by pixyzehn** [JohnSundell/Marathon#22]
This is a just suggestion. I'd like to hear your idea:)

How about `marathon uninstall <script-path> [<install-path>]` like this?

It just executes `rm -f "/usr/local/bin/<lowercased-name-of-script>"` or `rm -f "<install-path>/<lowercased-name-of-script>"`.
It successes only if marathon manages the same script name as the binary.

```sh
 pixyzehn ⮀ ~ ⮀ marathon help uninstall
💻  uninstall
----------
Uninstall a script at a given path as a binary

👉  Usage: 'marathon uninstall <script-path> [<install-path>]'

ℹ️  Marathon will delete the binary only if Marathon manages the same script name as the binary.
```

In addition, It's very difficult to select `uninstall` emoji 🤔

**Comment by JohnSundell** [comment]
@pixyzehn I'm not sure if I think it's a good idea to extend Marathon's scope to being able to perform uninstalls of binaries. The constraint you mentioned (only being able to uninstall binaries that have a cached script file), makes sense - but what if the user deletes the cache data? Don't think it's a good idea to rely on the cache data this way.

So while I see the convenience of being able to do an uninstall through Marathon, it's almost as easy to just remove the binary from `/usr/local/bin` 🙂

**Comment by pixyzehn** [comment]
I understand what you said, but I care about a consistency a little bit. For example, `marathon add` and `marathon remove`.
`marathon uninstall` has some problems to solve, so I'll think again.

How about if `marathon` has installed binaries lists like packages and cached scripts?

```
 pixyzehn ⮀ ~/Developer/projects/Require ⮀ ⭠ master ⮀ marathon list
📄  Scripts
----------
/Users/pixyzehn/Developer/sandbox-for-marathon/hoge.swift
/Users/pixyzehn/Developer/sandbox-for-marathon/fuga.swift

💻 Binaries
----------
hogehoge
```

**Comment by JohnSundell** [comment]
Sorry for taking a while to reply to this @pixyzehn. I agree that symetry is beautiful, but personally I don't really see this as such a big usecase. And given that it's so easy to just remove what you want to uninstall from `/usr/local/bin` I'm not sure if we should spend any time implementing and maintaining something like this...

**Comment by pixyzehn** [comment]
No problem:) I agree with the point you mentioned. I'll skip this feature for now👍 Thank you for giving me your thought!
