### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by rob-nash** [JohnSundell/Marathon#25]
Only a small issue but might be worth mentioning in ReadMe.

Roberts-MacBook-Pro:Marathon robertnash$ make
swift package --enable-prefetching update
Fetching https://github.com/johnsundell/files.git
Fetching https://github.com/johnsundell/unbox.git
Fetching https://github.com/johnsundell/wrap.git
Cloning https://github.com/johnsundell/files.git
Resolving https://github.com/johnsundell/files.git at 1.6.2
Cloning https://github.com/johnsundell/wrap.git
Resolving https://github.com/johnsundell/wrap.git at 2.1.0
Cloning https://github.com/johnsundell/unbox.git
Resolving https://github.com/johnsundell/unbox.git at 2.4.0
swift build --enable-prefetching -c release -Xswiftc -static-stdlib
Compile Swift Module 'Wrap' (1 sources)
Compile Swift Module 'Unbox' (1 sources)
Compile Swift Module 'Files' (1 sources)
Compile Swift Module 'MarathonCore' (24 sources)
Compile Swift Module 'Marathon' (1 sources)
Linking ./.build/release/Marathon
cp -f .build/release/Marathon /usr/local/bin/marathon
cp: /usr/local/bin/marathon: Permission denied
make: *** [install] Error 1

**Comment by JohnSundell** [comment]
What would you like to be mentioned in the README? Was the problem that you didn't have write access to `/usr/local/bin`? 🤔

**Comment by rob-nash** [comment]
I had to run 'sudo make'
My permissions are set up like so.
drwxr-xr-x  root  wheel  bin

**Comment by JohnSundell** [comment]
Ah, I understand. I'll add a note to the README, thanks! 👍

**Comment by JohnSundell** [comment]
✅  Done here: https://github.com/JohnSundell/Marathon/commit/7c353d4b21cad42444e1141b91b5e3da2baaaa5b
