### ISSUE TITLE
Hangs on run

### ISSUE THREAD

**Issue by rob-nash** [JohnSundell/Marathon#26]
Roberts-MacBook-Pro:Scripts robertnash$ cd ~/Desktop/Folder1/
Roberts-MacBook-Pro:Folder1 robertnash$ marathon create addSuffix
🐣  Created script at addSuffix.swift
✏️  Opening Addsuffix.xcodeproj/

ℹ️  Marathon will keep running, in order to commit any changes you make in Xcode back to the original script file
   Press any key once you're done

<img width="439" alt="screen shot 2017-04-03 at 10 39 44" src="https://cloud.githubusercontent.com/assets/14126999/24603776/19e5d606-185a-11e7-88ae-864c75de84d1.png">
Marathonfile = git@github.com:JohnSundell/Files.git
<img width="541" alt="screen shot 2017-04-03 at 10 42 11" src="https://cloud.githubusercontent.com/assets/14126999/24603807/3b9e05ac-185a-11e7-9784-230fcc0fa3b3.png">

Roberts-MacBook-Pro:Folder1 robertnash$ marathon run addSuffix "something"

hangs here

**Comment by JohnSundell** [comment]
@rob-nash Hi! Thanks for the report. Unfortunately I can't reproduce it on my machine, even if I first remove Files from Marathon. Let's debug it - can you:

1. Verify that the contents of your `Marathonfile` is exactly `git@github.com:JohnSundell/Files.git`?
2. Confirm that you have Swift 3.1 (bundled with Xcode 8.3) installed?
3. Run `$ marathon list` and show me what it outputs?

And let's take it from there 🙂

**Comment by rob-nash** [comment]
Hi John,

Thanks for the quick response.

Today it is not hanging! But I do get an error. Firstly, let's go through your steps.

1. Verified 👍
2. Confirmed 👍
3. Here you go:

Roberts-MacBook-Pro:~ robertnash$ marathon list
📄  Scripts
----------
/Users/robertnash/Desktop/Folder1/addSuffix.swift

👉  To remove either a package or the cached data for a script, use 'marathon remove'
Roberts-MacBook-Pro:~ robertnash$ marathon run addSuffix "something"
💥  Could not find a Swift script at 'addSuffix.swift'
👉  Please check that the path is valid and try again

**Comment by JohnSundell** [comment]
Are you running `marathon run addSuffix "something"` in the same folder as `addSuffix.swift` is located in? `run` takes a path to the script to run, and it looks like it can't find it.

**Comment by rob-nash** [comment]
Now I understand why it was hanging, only sometimes. Now I can reproduce the hanging consistently by performing this command in the same folder as addSuffix.swift.

Video attached shows the point at which it hangs.
[1.mov.zip](https://github.com/JohnSundell/Marathon/files/895708/1.mov.zip)

**Comment by JohnSundell** [comment]
@rob-nash Since I'm unable to reproduce this locally, do you mind helping a bit with debugging this issue?

- Generate an Xcode project for marathon by going to its repo and running `swift package generate-xcodeproj`.
- Open the generated `Marathon.xcodeproj`.
- Select the command line scheme, and go to `Product > Run...`
- Add the launch arguments `run`, `<path-to-addSuffix.swift>` (replace with actual path) and `"something"`.
- Run.

Does it still hang? If so, can you pause execution of the program and let me know where it hangs?
Also, can you make sure you are on the latest `master`?

**Comment by rob-nash** [comment]
Sorry for late reply. Yes I don't mind. I will take a look now.

**Comment by rob-nash** [comment]
It's failing here 

```swift
let rootFolder = try perform(fileSystem.createFolderIfNeeded(at: folderPath), orThrow: setupError)
```

couldNotPerformSetup("~/Desktop/Folder1/addSuffix.swift")
Program ended with exit code: 0

Might be permissions again.

**Comment by rob-nash** [comment]
Wait...why are we trying to create a folder at this point ?
'if needed' suggests that it might fail for a good reason and that we should ignore that error right ?
will take a look

**Comment by rob-nash** [comment]
Just pulled files and imported into iOS App target.

```swift
class ViewController: UIViewController {

    override func viewDidLoad() {
        super.viewDidLoad()
        
        let fileSystem = FileSystem()
        let path = "~/Desktop/Folder1/addSuffix.swift"
        do {
            let folder = try fileSystem.createFolderIfNeeded(at: path)
            print(folder)
        } catch let error {
            print(error)
        }
        
    }
    
}
```

No error. Output is
Folder(name: addSuffix.swift, path: /path/to/Desktop/Folder1/addSuffix.swift/)

Although, this is a file...not a folder. So will run Marathon again with use the path ~/Desktop/Folder1/

**Comment by rob-nash** [comment]
???

```swift
try Marathon.run(with: ["run", "something"], folderPath: "~/Desktop/Folder1/", printer: { value in
    print(value)
})
```
Output
'something' is not a valid command
```swift
try Marathon.run(with: ["run"], folderPath: "~/Desktop/Folder1/", printer: { value in
    print(value)
})
```
Output
Welcome to Marathon 🏃
----------------------
Marathon makes it easy to write, run and manage your Swift scripts.

These are the available commands:

🐣    create    Create new script at a given path and open it
✏️    edit      Edit a script at a given path
🗑    remove    Remove a package or the cache data for a script at a given path
🏃‍♀️    run       Run a script at a given path
💻    install   Install a script at a given path as a binary
📦    add       Add a package from a given URL to be able to use it from your scripts
📋    list      List all packages and cached script data
♻️    update    Update all added packages to their latest versions
ℹ️    help      Print these instructions

👉  You can also type a command you wish to know more about after 'help'
   For example: 'marathon help create' will show information about the 'create' command

🌏  For more information, go to https://github.com/johnsundell/marathon
Program ended with exit code: 0
```swift
try Marathon.run(with: ["addSuffix"], folderPath: "~/Desktop/Folder1/", printer: { value in
    print(value)
})
```
Output
Welcome to Marathon 🏃
----------------------
Marathon makes it easy to write, run and manage your Swift scripts.

These are the available commands:

🐣    create    Create new script at a given path and open it
✏️    edit      Edit a script at a given path
🗑    remove    Remove a package or the cache data for a script at a given path
🏃‍♀️    run       Run a script at a given path
💻    install   Install a script at a given path as a binary
📦    add       Add a package from a given URL to be able to use it from your scripts
📋    list      List all packages and cached script data
♻️    update    Update all added packages to their latest versions
ℹ️    help      Print these instructions

👉  You can also type a command you wish to know more about after 'help'
   For example: 'marathon help create' will show information about the 'create' command

🌏  For more information, go to https://github.com/johnsundell/marathon
Program ended with exit code: 0

**Comment by JohnSundell** [comment]
@rob-nash Really seems like a permissions problem. Marathon stores all of its data in a `~/.marathon` folder, which is what it seems to fail to create. It's very curious that the file path is `~/Desktop/Folder1` though. Did you modify Marathon's source code before installing it? Can you make sure that you have write permissions to your home folder (can't see any reason why you shouldn't have though).

**Comment by JohnSundell** [comment]
The reason you get `something is not a valid command` is because the first argument should be the execution path, as this is what gets given from the command line. Why are you envoking `Marathon.run` in code btw? Just for testing?

**Comment by rob-nash** [comment]
I attempted to debug the source code by running it and passing arguments in line with the source code.

If I execute the source code using the 'Marathon - My Mac' scheme the debug panel prints the same output that I see in the deployed terminal App. The programme runs to completion (Program ended with exit code: 0) so I am not given an opportunity to add arguments unless I modify the source code.

The permissions for my home directory is 

    drwxr-xr-x+ 40 robertnash                 staff   1360  6 Apr 11:24 robertnash

I don't actually know what the '+' symbol represents. Interestingly I can't launch the mac Spotify.app ! I have asked stacks for some input on this. http://stackoverflow.com/questions/43274359/cant-open-macos-app-what-does-the-symbol-represent-in-permissions

It now seems like my file system is being weird and I have no idea why it's behaving this way. This worried me a great deal. You may want to close this thread.

**Comment by rob-nash** [comment]
Then again...

I can see the ~/.marathon directory. The subdirectory 'Scripts' has the following

    -Users-robertnash-Desktop-Folder1-addSuffix

If this was a permissions problem the terminal App would return some sort of error, instead of hanging, right?

I'm sorry I can't give you any more insightful information than this. I will perform some more debugging over the weekend and if I find anything useful, I will post it here. You may want to close this thread anyway as the permissions problem I'm getting launching macOS Apps is likely the root cause, even if it doesn't make sense.

**Comment by JohnSundell** [comment]
Yeah it definetly seems like something is off with your file system. For reference here are the permissions of my home folder: `drwxr-xr-x@` (I know too little about permissions to decipher them though 😅).

If you're fine with closing this, then I think we can do it. You can always open a new issue if you find this to be a Marathon-specific problem.

Btw, you can totally set launch arguments in Xcode without having to modify the source code. Just go to the `Product > Run...` menu and set arguments there 🙂

**Comment by rob-nash** [comment]
Thanks John. Will get back to you if I learn something relevant.
