### ISSUE TITLE
Add support for adding packages using HTTPS-based git URL

### ISSUE THREAD

**Issue by johndpope** [JohnSundell/Marathon#27]
marathon add https://github.com/SwiftyJSON/SwiftyJSON.git

it does have a package.swift file and a tag. not sure why it doesn't work. 
https://github.com/SwiftyJSON/SwiftyJSON/issues/823

**Comment by pixyzehn** [comment]
@johndpope You can add by `marathon add git@github.com:SwiftyJSON/SwiftyJSON.git`.

```
 ✘ pixyzehn ⮀ ~ ⮀ marathon add git@github.com:SwiftyJSON/SwiftyJSON.git
📦  SwiftyJSON added
```

**Comment by JohnSundell** [comment]
@pixyzehn is right - use SSH-based cloning at it'll work 👍 But, we should totally add support for HTTPS-based clones. I'll rename the issue to reflect that.

**Comment by garricn** [comment]
@JohnSundell If one were interested in implementing this, where would one begin to look? I'll have a look around and see if I might be able to do it. No promises though :)

**Comment by JohnSundell** [comment]
@garricn Actually, this has already been fixed, just forgot to close the ticket 😱
