### ISSUE TITLE
How to open the xcode project again?

### ISSUE THREAD

**Issue by onmyway133** [JohnSundell/Marathon#3]
Hi John, nice library 👍 . I'm starting to use Marathon, when running `marathon create helloWorld "import Foundation; print(\"Hello world\")"` it opens the source file in Xcode, which is handy. But after that, in Finder I only see `helloWorld.swift`, how can I open it it Xcode again?

Also, it seems the scheme is duplicated

![marathon](https://cloud.githubusercontent.com/assets/2284279/23895466/1af70eca-08a6-11e7-9914-405b351d9092.png)

**Comment by JohnSundell** [comment]
Happy you like Marathon @onmyway133! 😄 Marathon copies your script into its own directory (`~/.marathon`), and uses the Swift Package Manager to create an Xcode project for your script there. This is to avoid having to clutter your folders with files like Xcode projects and dependency checkouts.

To edit the script using Xcode again, simply call `marathon edit <path-to-script>`.

Marathon doesn't actually generate the Xcode projects, the Swift Package Manager does, but I don't think the schemas are duplicated - there's an Xcode bug that makes them both appear like command line tools, but one of them is actually a Swift framework.

**Comment by onmyway133** [comment]
@JohnSundell I think that answers my question. `marathon edit` to the rescue
