### ISSUE TITLE
[Bug] marathon create script --no-open

### ISSUE THREAD

**Issue by pixyzehn** [JohnSundell/Marathon#31]
```sh
pixyzehn ⮀ ~/Developer/sandbox-for-marathon ⮀ marathon create script --no-open
🐣  Created script at script.swift
 pixyzehn ⮀ ~/Developer/sandbox-for-marathon ⮀ cat script.swift
--no-open%
```
I think it's better to add `"import Foundation\n\n"` instead of `--no-open`.

**Comment by pixyzehn** [comment]
I'll fix this issue after merging https://github.com/JohnSundell/Marathon/pull/29.

**Comment by JohnSundell** [comment]
I can take car of it now, I have some spare time 😄

**Comment by JohnSundell** [comment]
Fixed in https://github.com/JohnSundell/Marathon/commit/692abd55377ae970f1d26c64984bf9c16b07a597 🎉 Great find @pixyzehn!

**Comment by pixyzehn** [comment]
Looks perfect! Thanks @JohnSundell !!
