### ISSUE TITLE
Inline dependency resolution

### ISSUE THREAD

**Issue by JohnSundell** [JohnSundell/Marathon#34]
This is an idea @aciidb0mb3r and me have been discussing over Slack, which I think would be really cool to implement.

Currently, Marathon supports defining dependencies for scripts using a `Marathonfile` - which works really well for most usecases. However, sometimes you want to distribute a script _just_ as its `.swift` file (and not have to include any additional supporting files). This is where inline dependency resolution comes in.

The suggestion is to enable `imports` to be annotated with the URL that the imported package can be found as, so that Marathon can analyze the imports, and add any missing packages (just as it does with a `Marathonfile`). Like this:

```swift
import Files // git@github.com:JohnSundell/Files.git

print(FileSystem().currentFolder.path)
```

The reason we use comments instead of something fancy (like an `@` sign) is because we want every Marathon script to still be 100% valid Swift, so that it can be run both with and without Marathon.

**Comment by pixyzehn** [comment]
Looks good!! I'd like to implement in a more declarative way to avoid unintentional imports.

For instance, 
```swift
import Files // marathon:git@github.com:JohnSundell/Files.git

print(FileSystem().currentFolder.path)
```
This idea is inspired by https://github.com/realm/SwiftLint#disable-rules-in-code.

**Comment by JohnSundell** [comment]
Great idea @pixyzehn, let's go with that 👍
