### ISSUE TITLE
Wired errors during installation on Raspberry Pi with Ubuntu 16.04.2

### ISSUE THREAD

**Issue by darthpelo** [JohnSundell/Marathon#37]
Hi @JohnSundell! 
I want to report this error also if I know that Swift on ARM is not right now a stable environment. So if it's to hard to figure out the problem no worries, you can close this issue :)

The machine is a Raspberry Pi 2 with Ubuntu 16.04.2.
Swift version:
```
ubuntu@ Marathon (master)$ swift --version
Swift version 3.1 (swift-3.1-RELEASE)
Target: armv7-unknown-linux-gnueabihf
```

The errors are the same using the **Make** or the **SPM**:
```
Compile Swift Module 'Wrap' (1 sources)
Compile Swift Module 'Unbox' (1 sources)
Compile Swift Module 'Require' (1 sources)
Compile Swift Module 'Files' (1 sources)
Compile Swift Module 'ShellOut' (1 sources)
/home/ubuntu/Marathon/.build/checkouts/wrap.git-1764762263/Sources/Wrap.swift:264:26: error: use of unresolved identifier 'RegularExpression'
        let regex = try! RegularExpression(pattern: "(?<=[a-z])([A-Z])|([A-Z])(?=[a-z])", options: [])
                         ^~~~~~~~~~~~~~~~~
Foundation.NSRegularExpression:1:12: note: did you mean 'NSRegularExpression'?
open class NSRegularExpression : Foundation.NSObject, NSCopying, NSCoding {
           ^
/home/ubuntu/Marathon/.build/checkouts/require.git--488267411/Sources/Require.swift:31:29: error: use of unresolved identifier 'NSException'
            let exception = NSException(
                            ^~~~~~~~~~~
SwiftGlibc.exception:1:15: note: did you mean 'exception'?
public struct exception {
              ^
Foundation.NSExpression:1:12: note: did you mean 'NSExpression'?
open class NSExpression : Foundation.NSObject, NSSecureCoding, NSCopying {
           ^
Foundation.NSExceptionName:2:15: note: did you mean 'NSExceptionName'?
public struct NSExceptionName : RawRepresentable, Equatable, Hashable, Comparable {
              ^
<unknown>:0: error: build had 2 command failures
error: exit(1): /opt/swift/swift-3.1/usr/bin/swift-build-tool -f /home/ubuntu/Marathon/.build/release.yaml
Makefile:4: recipe for target 'install' failed
make: *** [install] Error 1
```
I have no idea why the compiler is "confused" with RegularExpression and NSExpression :(

Thanks in advance!

**Comment by JohnSundell** [comment]
Hi @darthpelo!

Thanks a lot for the report! I personally haven't had the chance to try installing Marathon on Linux yet, but it would be awesome to make it work on that platform as well as on macOS 👍 

As far as I can tell there are two concrete tasks from looking at the build errors:

- [ ] Make [ShellOut](https://github.com/johnsundell/shellout) compile for Linux (it uses `NSException`, which is not part of the open source Swift version of `Foundation`).
- [ ] Add a typealias for `NSRegularExpression` -> `RegularExpression`, so that it builds on Linux.

Since I'm not that much into Swift on Linux myself yet (it's still on my todo, since a year back 😅), I'd love help from the community on this one 😄

**Comment by darthpelo** [comment]
Thanks for the reply @JohnSundell :)
If I have time today or tomorrow I will try to help.

**Comment by JohnSundell** [comment]
@darthpelo That would be really awesome 🎉 I think for ShellOut we can probably just surround the code using `NSException` with `#if !platform(Linux)`.

**Comment by JohnSundell** [comment]
@darthpelo Sorry, my bad - it's not ShellOut that contains the `NSException` code - it's Require 😅

**Comment by darthpelo** [comment]
@JohnSundell thanks! I was a little bit lost 😄

**Comment by darthpelo** [comment]
@JohnSundell short update.

These are the first result after the build of my Marathon [fork](https://github.com/darthpelo/Marathon).
 
**Ubuntu 16.04 (Vmware image)**
![screen shot 2017-04-11 at 10 54 46](https://cloud.githubusercontent.com/assets/1339000/24900835/72e62e12-1ea5-11e7-88b1-4a0a1a879c80.png)

**Ubuntu 16.04 (Raspberry Pi)**
![screen shot 2017-04-11 at 10 54 21](https://cloud.githubusercontent.com/assets/1339000/24900853/873e1b7c-1ea5-11e7-9bd6-865f47561149.png)

**My Mac**
![screen shot 2017-04-11 at 10 58 48](https://cloud.githubusercontent.com/assets/1339000/24900978/e42ec55c-1ea5-11e7-8d7e-d796ce58ff37.png)

Regarding the `DistapatchQueue` issue, the solution it's easy: import `Dispatch` in Script.swift
```swift
#if os(Linux)
    import Dispatch
#endif
```

Right now I builded in develop and not release because `swift build -c release -Xswiftc -static-stdlib`, if I understood, needs Xcode, right?

**Comment by JohnSundell** [comment]
@darthpelo That is really awesome 👏 Yeah, we can build `release` on Linux, but not statically link the standard library (AFAIK). So just `swift build -c release` on Linux. Feel free to open PRs with your changes once you're ready and we'll get them merged ASAP. Super excited about getting Marathon up and running on Linux. Did you try running the tests btw?

**Comment by darthpelo** [comment]
@JohnSundell yes `swift build -c release` it's enough. Right now only `install` doesn't work and return a generic `💥  Failed to compile script`.

About tests: 
now I am testing Marathon, Required and Wrap on my Mac to be sure that I did not broke anything 😅. Then I need to understand how tests work with Linux.

**Comment by darthpelo** [comment]
@JohnSundell Marathon and Wrap tests are all ✅ on Mac.  
On Linux platform only Wrap has all tests ✅.

I have 4 ❌ https://github.com/darthpelo/Marathon/pull/1 but I'm not sure about the causes.
These are the errors:

**testAddingAndRemovingRemotePackage**
```
Test Case 'MarathonTests.AddingAndRemovingRemotePackage' started at 12:37:40.118
<EXPR>:0: error: MarathonTests.AddingAndRemovingRemotePackage : threw error "💥  Cannot remove package 'files' - no such package has been added
👉  Did you mean to remove the cache data for a script? If so, add '.swift' to its path
   To list all added packages run 'marathon list'"
Test Case 'MarathonTests.AddingAndRemovingRemotePackage' failed (9.49 seconds)
```
**testInstallingLocalScript**
```
Test Case 'MarathonTests.testInstallingLocalScript' started at 12:40:04.579
<EXPR>:0: error: MarathonTests.testInstallingLocalScript : threw error "💥  Failed to compile script"
Test Case 'MarathonTests.testInstallingLocalScript' failed (18.473 seconds)
```
**testInstallingRemoteScriptWithDependencies**
```
Test Case 'MarathonTests.testInstallingRemoteScriptWithDependencies' started at 12:40:23.052
<EXPR>:0: error: MarathonTests.testInstallingRemoteScriptWithDependencies : threw error "💥  Failed to compile script"
Test Case 'MarathonTests.testInstallingRemoteScriptWithDependencies' failed (17.406 seconds)
```
**testUsingMarathonfileToInstallDependencies**
```
Test Case 'MarathonTests.testUsingMarathonfileToInstallDependencies' started at 12:40:49.292
<EXPR>:0: error: MarathonTests.testUsingMarathonfileToInstallDependencies : threw error "💥  Failed to compile script"
Test Case 'MarathonTests.testUsingMarathonfileToInstallDependencies' failed (26.146 seconds)
```

If I'm right are not related to Required and Wrap, so for now I would like to create the PRs for these two. 

What do you think about it?

**Comment by darthpelo** [comment]
@JohnSundell I close this issue :)
