### ISSUE TITLE
marathon add is not responding

### ISSUE THREAD

**Issue by onmyway133** [JohnSundell/Marathon#4]
Hi John,

I can create and run the library now. All are great. Then I add another framework with this command, I run `marathon add git@github.com:JohnSundell/Files.git`. I waited for some time but it seems not responding, and there is no `Marathonfile` generated.

I'm on `macOS 10.12.3` and Swift `Apple Swift version 3.0.2 (swiftlang-800.0.63 clang-800.0.42.1)
Target: x86_64-apple-macosx10.9`

**Comment by JohnSundell** [comment]
Marathon doesn't generate any `Marathonfile` for your dependencies - instead a `Marathonfile` is used to *declare* dependencies for your own scripts.

Just to make sure; do you have git and an ssh key for GitHub setup on this machine? What Marathon does when you run `add` is to resolve the latest version for the given package URL using `git ls-remote`.

Could you try running `git ls-remote --tags git@github.com:JohnSundell/Files.git` in your terminal, and see if it produces any output?

I'm also planning to add more informative output to Marathon, to report back what steps it's doing, and have some timeouts for cases like this 🙂

**Comment by onmyway133** [comment]
@JohnSundell oh ja, I used to use `https` instead of `git`. Adding more informative output would be nice, looking forward
