### ISSUE TITLE
Fails to download and install script.

### ISSUE THREAD

**Issue by kobusb** [JohnSundell/Marathon#40]
Running 
`marathon install https://raw.githubusercontent.com/JohnSundell/Playground/master/Sources/Playground.swift`

Output:
``` bash
🏃  Downloading script...
   Saving script...
   Resolving Marathonfile...
   Saving Marathonfile...
   Updating packages...
💥  Failed to download script from 'https://raw.githubusercontent.com/JohnSundell/Playground/master/Sources/Playground.swift'
👉  Make sure that the URL is reachable, and that it contains a valid Swift script
```

Output from `marathon list`:
```
ℹ️  No packages or script data has been added to Marathon yet
```

Tried the above `marathon install` in the following shells: `fish`, `bash`, `zsh` 

Running `curl https://raw.githubusercontent.com/JohnSundell/Playground/master/Sources/Playground.swift` successfully downloads the file

**Comment by JohnSundell** [comment]
Hi @kobusb! Thanks for the report! 👍 

That's very curious, I was expecting `marathon list` to contain packages. Just to rule it out; do you have an SSH-key setup with GitHub to enable you to clone over SSH? It seems like Marathon is failing to install the packages declared in Playground's `Marathonfile`.

**Comment by kobusb** [comment]
Yeah I do have SSH set up, and I'm able to manually clone the dependencies in the Marathonfile:
`git clone git@github.com:johnsundell/xgen.git`
`git clone git@github.com:johnsundell/files.git`
`git clone git@github.com:johnsundell/shellout.git`
All the above succeed no problem.

**Comment by kobusb** [comment]
Done some debugging, and running from Xcode, it throws on this line in PackageManager.swift:
`try generatedFolder.moveToAndPerform(command: "swift package --enable-prefetching update")`

`swift-package: error: unknown command: --enable-prefetching`

**Comment by kobusb** [comment]
Just read the Requirements, and I see you did mention Xcode 8.3 is required. Sorry about that, should have read that more carefully. 😢

**Comment by JohnSundell** [comment]
@kobusb Yeah, that's the issue! Swift Package Manager prefetching was introduced in Swift 3.1, so that's why it's failing. No worries, happy we found the source of the problem 😄 Mind if I close this issue?

**Comment by kobusb** [comment]
Sure, you may close it. Thanks for the help. 🙌

**Comment by JohnSundell** [comment]
@kobusb No problems! 👍
