### ISSUE TITLE
Question: Marathon remove

### ISSUE THREAD

**Issue by rob-nash** [JohnSundell/Marathon#46]
I run marathon list and I could see that I had packages and scripts installed. Running marathon remove was a little more confusing. I'm not 100% sure what marathon remove actually does.

marathon remove helloWorld
-deletes cached data

marathon remove /path/to/helloWorld.swift
-deletes the script file

Is that right ?

I don't understand 'cached data'. What is getting cached exactly ?

I was expected marathon remove to be the inverse of marathon create. Or maybe it requires an option to do a force remove all maybe

```
marathon remove -a helloWorld
```

**Comment by JohnSundell** [comment]
@rob-nash Have you run `marathon help remove`? Remove can be used for 2 purposes:

1. Removing a package that you've added using `marathon add` (like `marathon remove Files`)
2. Clean up the cache data for a script (like `marathon remove /path/to/helloWorld.swift`)

To speed up the compilation and execution of your scripts, Marathon stores cache data (like cloned packages, metadata, etc) in its directory. You can see exactly what Marathon stores by going to `~/.marathon/scripts`.

Does that answer your question? 🙂

**Comment by rob-nash** [comment]
Yeeaaarp!
Thanks
