### ISSUE TITLE
Press any key when done - not true

### ISSUE THREAD

**Issue by rob-nash** [JohnSundell/Marathon#47]
I know this isn't a compelling issue, but it's worth noting I guess.

After using marathon create helloWorld marathon keeps running in order to commit any changes. 'Press any key once you're done' isn't quite right. If I use the return key, then it works. But if I press the 'd' key nothing happens.

<img width="830" alt="screen shot 2017-04-12 at 19 57 49" src="https://cloud.githubusercontent.com/assets/14126999/24974568/86056704-1fba-11e7-8983-bc75b5e5f8cf.png">

**Comment by JohnSundell** [comment]
Thanks for reporting this @rob-nash - will update the wording to tell the user to press the return key 👍

**Comment by JohnSundell** [comment]
Fixed in https://github.com/JohnSundell/Marathon/commit/ace4101b42ec7a44f8bca128cf5e760bb7042775!
