### ISSUE TITLE
Case sensitive issue with remove package on Linux

### ISSUE THREAD

**Issue by darthpelo** [JohnSundell/Marathon#50]
Hi @JohnSundell I understand why test `testAddingAndRemovingRemotePackage` failed on Linux with this error:
```bash
<EXPR>:0: error: MarathonTests.AddingAndRemovingRemotePackage : threw error "💥  Cannot remove package 'files' - no such package has been added
👉  Did you mean to remove the cache data for a script? If so, add '.swift' to its path
   To list all added packages run 'marathon list'"
```
The issue is the package name used in the test
```swift
// Remove the package
try run(with: ["remove", "files"])
```
The real name of the package is Files, but on macOS 10.12.4 doesn't matter if we pass the string with the first letter lowercase.
On my virtual machine with Ubuntu 16.04, instead, this difference became an issue. I changed the test in this way and it works:
```swift
// Remove the package
#if os(Linux)
    try run(with: ["remove", "Files"])
#else
     try run(with: ["remove", "files"])
#endif
```

After that I checked the function `func removePackage(named name: String, shouldUpdatePackages: Bool = true) throws -> Package` inside `PackageManager.swift` and I think that this is the command that throws the exception
```swift
 let packageFile = try perform(folder.file(named: name),
                               orThrow: Error.unknownPackageForRemoval(name))
```

At this point my question is: how `folder.file(named: name)` works? Is it inside the `Files` package?

Thanks!

**Comment by JohnSundell** [comment]
Great catch @darthpelo! Let's just update the test to use the proper casing 👍 If the file system is case sensitive then using the improper casing is a user error and should throw anyway, so I don't think that Marathon should be "smart enough" to handle it.

**Comment by darthpelo** [comment]
@JohnSundell I agree 🙂

**Comment by darthpelo** [comment]
@JohnSundell sorry for the silence but Easter lunches/dinners and daily work (new iOS project kick off) keep me away from Marathon 😅 I will back in the weekend 💪

**Comment by JohnSundell** [comment]
@darthpelo No problem at all - same for me 🐥 No stress - just work on it whenever you have time - I really appreciate your help 🚀

**Comment by JohnSundell** [comment]
This has now been fixed, all tests passes on Linux 🎉
