### ISSUE TITLE
Error Erasure

### ISSUE THREAD

**Issue by rob-nash** [JohnSundell/Marathon#52]
Marathon create was failing for me and I couldn't understand why without debugging the project. I discovered that my ssh key was not added as an identify to my ssh-agent so a pull from source was failing. 

This error did not appear in-line in the terminal but it would have been useful if it did. The terminal just hanged actually.

The create command calls upon the following at some point:

```swift
func edit(arguments: [String], open: Bool) throws {
    do {
        let path = try editingPath(from: arguments)

        if open {
            let relativePath = path.replacingOccurrences(of: folder.path, with: "")
            printer.output("✏️  Opening \(relativePath)")

            try shellOut(to: "open \"\(path)\"", printer: printer)

            if path.hasSuffix(".xcodeproj/") {
                printer.output("\nℹ️  Marathon will keep running, in order to commit any changes you make in Xcode back to the original script file")
                printer.output("   Press the return key once you're done")

                startCopyLoop()
                _ = FileHandle.standardInput.availableData
                try copyChangesToSymlinkedFile()
            }
        }
    } catch {
        throw Error.editingFailed(name)
    }
}
```

By lifting the try editingPath function out of the do closure, I was able to push the ShellOut error to the surface.

```swift
func edit(arguments: [String], open: Bool) throws {
        
    let path = try editingPath(from: arguments)
    
    do {
        ...
   }
}
```

And capture it here

```swift
do {
    try Marathon.run()
} catch let error as ShellOutError {
    print(error.message)
    print(error.output)
} catch {
    print("\(error)")
}
```
The marathon project is great, but this kind of error erasure happens quite a lot. What is your opinion on printing extraneous errors like this ? Do you have a plan for handling extraneous errors?

Thanks

**Comment by JohnSundell** [comment]
@rob-nash This is why the `--verbose` flag was added. It prints all the underlying commands that Marathon issues on the command line, as well as any return values and errors thrown. I personally prefer to keep error reporting simple on the surface, with the option to "dig in deeper" if needed. The `--verbose` flag should serve that purpose here. I'm also planning on adding more reporting on the "steps" that Marathon takes when executing a command, as well as better error reporting for issues like this.

Hope that answers your question / addresses your concerns 🙂

**Comment by rob-nash** [comment]
Ah! A flag --verbose ! Very good. I have another hang though and I don't know what the error is. Will have to debug again.
<img width="910" alt="screen shot 2017-04-17 at 18 21 04" src="https://cloud.githubusercontent.com/assets/14126999/25097052/ccf5d656-239a-11e7-99ce-f65e68815d1e.png">

**Comment by JohnSundell** [comment]
@rob-nash That looks like `swift package generate-xcodeproj` is hanging (or taking a long time, which it can sometimes do). Currently, even with the `--verbose` flag, underlying commands (in this case, the ones that `swift package generate-xcodeproj` is issuing) are still not printed. My guess is that some dependency is failing to clone/update. Can you show me the output of `marathon list`?

**Comment by rob-nash** [comment]
It was the ssh agent issue I mentioned earlier. It is a re occurring problem for me at the moment. It's under control but useful for this thread as it highlights the issue of error logging quite well. You can see that even with the verbose flag enabled, the shell out error isn't written. I don't mind providing a fix for this but I guess this issue might be a design pattern that extend beyond this call sight. Unless you think this is just a one time issue?

**Comment by rob-nash** [comment]
That might not be very clear. I'm quite drunk at the moment. Maybe we should talk about this when I am not drunk.

**Comment by JohnSundell** [comment]
@rob-nash can this be closed?

**Comment by rob-nash** [comment]
Ha yes. Sorry forgot about this.
