### ISSUE TITLE
enhancement - error trapping /backtrace /pipefail

### ISSUE THREAD

**Issue by johndpope** [JohnSundell/Marathon#54]
When bash scripting - it's a frequent challenge that there will be error conditions encountered which will cause script to abort. 

eg. 
<img width="702" alt="screen shot 2017-04-25 at 10 20 53 am" src="https://cloud.githubusercontent.com/assets/289994/25390224/e766778c-29a0-11e7-81fa-fe9065815158.png">

This script has been well received by people in community to trap a complex script executing multiple commands 
https://github.com/niieani/bash-oo-framework#error-handling-with-exceptions-and-throw

http://stackoverflow.com/questions/64786/error-handling-in-bash
```

#!/bin/bash

source 'lib.trap.sh' // by including this - a complete picture is revealed on error states encountered 

echo "doing something wrong now .."
echo "$foo"

exit 0
```

Naturally this would only make sense when executing other commands from terminal using Marathon. 

This may take some time to get right - but would fit nicely into this to help replace bash scripts -> swift.

![0ubol](https://cloud.githubusercontent.com/assets/289994/25390943/f5108ca4-29a2-11e7-9f1e-698458873097.jpg)

**Comment by JohnSundell** [comment]
@johndpope I don't really understand what you mean by this issue. Could you clarify? Do you want to see some change to the way Marathon reports errors?

**Comment by JohnSundell** [comment]
Ping @johndpope

**Comment by johndpope** [comment]
My intention behind this is to simplify porting bash scripts across to swift for newbies. 
In this one thing that can pop up / trip up users is error handling. 
eg. a simple mkdir Folder / may error because the folder exists.
Now obviously there's superior native swift commands that should be run here in stead... 


but say we execute a command from within swift script / being able to trap the error bubbling up could be worthwhile incorporating into this library. 

The above script encapsulates some catch all  so any errors are saved
https://gist.github.com/fragolinux/b2dac0ec7315ba9fda0e6e17cf34d8c0

also seems laborious that users would need to wrap following commands to execute a single bash command.


```
    let task = Process()

    // Set the task parameters
    task.launchPath = "/bin/ls"
    task.arguments = ["-laF@" , filePath]

    // Create a Pipe and make the task
    // put all the output there
    let pipe = Pipe()
    task.standardOutput = pipe

    // Launch the task
    task.launch()

    // Get the data
    let data = pipe.fileHandleForReading.readDataToEndOfFile()
    let output = NSString(data: data, encoding: String.Encoding.utf8.rawValue)

    print(output!)

```

presuming something went wrong / it would good to be able to trap error.

**Comment by JohnSundell** [comment]
I think what you're looking for is something like [ShellOut](https://github.com/johnsundell/shellout) - it enables you to easily call out into Bash and return the result (or throw). Marathon has no opinion about what a script contains, or how it performs error handling. It simply runs scripts and returns the outcome (either through `STDOUT` for normal output or `STDERR` for errors).

**Comment by johndpope** [comment]
Brilliant. thanks John.

You should add it into readme as it could be very helpful and complimentary to marathon.

**Comment by johndpope** [comment]
Brilliant. thanks John.

You should add it into readme as it could be very helpful and complimentary to marathon.
