### ISSUE TITLE
Installation via make stalls 

### ISSUE THREAD

**Issue by icanzilb** [JohnSundell/Marathon#56]
I tried to install Maraton via the first installation method (cloning and running `make`) but the installation stalls either at fetching releases or shellout 🤔 I ran this more than 5 times and it still didn't go through.

![image](https://cloud.githubusercontent.com/assets/633862/25536760/9713aa42-2c44-11e7-83b8-5bbabcb65ea4.png)

Has anyone else ran into that issue?

**Comment by icanzilb** [comment]
looks like it was related to Sierra issue when it doesn't use Keychain to store ssh access credentials. Following the advice here: https://www.cyberciti.biz/faq/howto-fix-macos-keeps-asking-my-ssh-passphrase-since-i-updated-to-sierra/ now the installation goes through.

**Comment by JohnSundell** [comment]
This is a quite common issue actually - I'll add some pre-checks to make sure that the SSH setup is good to go, so that a better (or any) error message will be thrown before even attempting the install - instead of stalling it 😄
