### ISSUE TITLE
[Improvement] Install via Homebrew

### ISSUE THREAD

**Issue by bennokress** [JohnSundell/Marathon#59]
I don't know how much effort it would take to make this available via homebrew, but I guess it would be easier to install, update and maintain for less experienced users.

**Comment by JohnSundell** [comment]
@bennokress That's a great idea! 👍 Homebrew has a rule that creators of a project can't submit their own work - but I'd love it if someone from the community added Marathon to Homebrew.

**Comment by bennokress** [comment]
Okay, I'm very busy at the moment and have no experience with creating a hombrew formula or ruby for that matter, but I'll look into it, if it isn't done by someone else in the meantime.

This seems to be the tutorial, if someone is interested: [Formula Cookbook](http://docs.brew.sh/Formula-Cookbook.html)

**Comment by aksswami** [comment]
@JohnSundell I was trying to create a `brew formula` for marathon, but faced some issue. I think, only contributor of the repo will be able to fix these issues. Here are the warning from a forked repo formula.

```
marathon:
  * C: 2: col 9: Description shouldn't include the formula name  // This can be fixed via changing description.
  * Formula should have a homepage. // We can set up GitHub pages for home page of Marathon
  * GitHub fork (not canonical repository)
  * GitHub repository not notable enough (<20 forks, <20 watchers and <50 stars)
  * GitHub repository too new (<30 days old)
Error: 5 problems in 1 formula
```

Here is the formula file :- https://gist.github.com/aksswami/2e8e800c06c5a8f385cef0b40c945ba3

We also need to the tag for version release, so that we can access `.zip` or `tar.gz` bundle for the repo.

**Comment by JohnSundell** [comment]
@aksswami Yeah you need to point the formula to this repo, not to your fork. For homepage, you can just use `https://github.com/johnsundell/marathon`. I can create a release during this upcoming weekend, have a few things I want to take care of before tagging a release.

Awesome that you're starting to look into this! I really appreciate it 👍

**Comment by aksswami** [comment]
@JohnSundell I will complete the formula and create a PR to homebrew-core once you release the first version of Marathon. To create a homebrew formula we need to have a release, that's why I pointed to my fork for testing purpose. 

Looking forward to Marathon release.

**Comment by PoissonBallon** [comment]
Hi, 
Any news about this ? 
Thanks to @JohnSundell for marathon btw 
cc @aksswami

**Comment by orta** [comment]
Ping, this one is blocked by a release of Marathon @JohnSundell  - might be worth a 1.0?

**Comment by JohnSundell** [comment]
@orta @PoissonBallon @aksswami Sorry for the delay on this one - I have just released Marathon version `1.0.0` 🎉 So Homebrew support can now be added 🚀

**Comment by orta** [comment]
Thanks John,  I took a stab at the homebrew setup but will need a patch release I think to make it work, PR incoming.

**Comment by orta** [comment]
With the changes in https://github.com/JohnSundell/Marathon/pull/118

This can be submitted (with updated version + SHA)

```ruby
class Marathon < Formula
  desc "Marathon makes it easy to write, run and manage your Swift scripts 🏃"
  homepage "https://github.com/JohnSundell/Marathon"
  url "https://github.com/JohnSundell/Marathon/archive/1.0.0.tar.gz"
  sha256 "b6cb5ac6d765fd99e74a7b1a0e9400985ce80860ec2612d10ffbc7a75249a663"

  def install
    system "make", "install"
  end

  test do
    system "#{bin}/marathon", "help"
  end
end
```

**Comment by JohnSundell** [comment]
Perfect, just merged the PR! 👍 Who wants to take this forward and submit the formula to Homebrew? 😄

**Comment by orta** [comment]
@JohnSundell it'll need a release too 🍡

**Comment by JohnSundell** [comment]
Of course 🤦‍♂️ Done ✅

**Comment by orta** [comment]
Thanks: turns out I couldn't use the makefile stuff anyway, (swift build sandboxing with homebrew issues) - could move into the makefile as a non-sandbox'd build though

PR: https://github.com/Homebrew/homebrew-core/pull/17266

**Comment by orta** [comment]
Hrm, so the name marathon already exists inside brew/cask (the Mac .app section of homebrew) - which means that we can't submit as "marathon". 

Opinions on "marathon-cli" or "marathon-swift" or something like that?

**Comment by JohnSundell** [comment]
@orta bummer 😕 but I think `marathon-swift` is a good option - if we were to use `marathon-cli` it might look like it's a CLI for the "other Marathon" 🙂

**Comment by JohnSundell** [comment]
@orta really awesome that you're doing this - it's gonna be a huge improvement for Marathon 👍

**Comment by orta** [comment]
No worries will update, getting this on homebrew is a [blocker on danger-swift](https://github.com/danger/danger-swift/issues?utf8=✓&q=is%3Aissue%20marathon) - as I need a reasonable way to do swift system-dependencies.

**Comment by orta** [comment]
Done, and updated docs in #124 

<img width="873" alt="screen shot 2017-08-31 at 09 50 26" src="https://user-images.githubusercontent.com/49038/29926595-e68d4994-8e31-11e7-9975-b16a409f7821.png">

**Comment by JohnSundell** [comment]
That is AMAZING! 🎉 Thanks a lot @orta - I'm super excited about this, huge improvement for the project! 🚀

**Comment by JohnSundell** [comment]
Also big thanks to you @bennokress & @aksswami & everyone else who has done work on this 👍

**Comment by dyna-dot** [comment]
I think you should have a good look once again
