### ISSUE TITLE
swift build -c release -Xswiftc -static-stdlib -> same-type requirement makes generic parameter 'Element' non-generic 

### ISSUE THREAD

**Issue by LuisMDeveloper** [JohnSundell/Marathon#70]
Error while compiling:

`/Users/luismanuelramirezvargas/Projects/Marathon/Packages/Releases-1.0.6/Sources/Array+Version.swift:10:38: error: same-type requirement makes generic parameter 'Element' non-generic
public extension Array where Element == Version {
                                     ^
/Users/luismanuelramirezvargas/Projects/Marathon/Packages/Releases-1.0.6/Sources/Array+Version.swift:12:34: error: reference to generic type 'Array' requires arguments in <...>
    func withoutPreReleases() -> Array {
                                 ^
                                      <Any>
<unknown>:0: note: generic type 'Array' declared here
<unknown>:0: error: build had 1 command failures`

Full stacktrace:
`$ swift build -c release -Xswiftc -static-stdlib
Cloning https://github.com/JohnSundell/Files.git
HEAD is now at 284d85d Merge pull request #11 from yageek/feature/currentFolder
Resolved version: 1.8.0
Cloning https://github.com/JohnSundell/Unbox.git
HEAD is now at ba42e01 Merge pull request #164 from hartbit/set-unboxable-collection
Resolved version: 2.4.0
Cloning https://github.com/JohnSundell/Wrap.git
HEAD is now at d6b953b Merge pull request #35 from darthpelo/master
Resolved version: 2.1.1
Cloning https://github.com/JohnSundell/ShellOut.git
HEAD is now at 38cd16d README: Update for new series of commands + path API
Resolved version: 1.1.0
Cloning https://github.com/JohnSundell/Require.git
HEAD is now at 44d5266 Remove whitespace & improve code formatting
Resolved version: 1.0.2
Cloning https://github.com/JohnSundell/Releases.git
HEAD is now at 787caab Use HTTPS instead of SSH for cloning dependencies
Resolved version: 1.0.6
Compile Swift Module 'Require' (1 sources)
Compile Swift Module 'ShellOut' (1 sources)
Compile Swift Module 'Wrap' (1 sources)
Compile Swift Module 'Unbox' (1 sources)
Compile Swift Module 'Files' (1 sources)
Compile Swift Module 'Releases' (4 sources)
/Users/user/Projects/Marathon/Packages/Releases-1.0.6/Sources/Array+Version.swift:10:38: error: same-type requirement makes generic parameter 'Element' non-generic
public extension Array where Element == Version {
                                     ^
/Users/user/Projects/Marathon/Packages/Releases-1.0.6/Sources/Array+Version.swift:12:34: error: reference to generic type 'Array' requires arguments in <...>
    func withoutPreReleases() -> Array {
                                 ^
                                      <Any>
<unknown>:0: note: generic type 'Array' declared here
<unknown>:0: error: build had 1 command failures
error: exit(1): /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-build-tool -f /Users/user/Projects/Marathon/.build/release.yaml`

**Comment by JohnSundell** [comment]
Hi @LuisMDeveloper 👋 Marathon requires Swift 3.1, so please update to Xcode 8.3 and try again 👍

**Comment by JohnSundell** [comment]
Closing this for now. @LuisMDeveloper let me know if you need any other assistance 🙂
