### ISSUE TITLE
Script hangs when printing too much data

### ISSUE THREAD

**Issue by jimabc** [JohnSundell/Marathon#8]
Running the following Marathon script in Terminal hangs indefinitely, while completing promptly in Xcode.

```
print((0...99999).reduce("") { $0 + ",\($1)" })
print("👍  All done!")
```

I discovered this while attempting to recursively print filenames from a large directory.

**Comment by JohnSundell** [comment]
Fixed in https://github.com/JohnSundell/Marathon/commit/f1d2ec8f803301b0fdbcbebc931afc9131e624b8 🎉 
Thanks a lot @jimabc for reporting this 👍
