### ISSUE TITLE
clarification on adding / (if it not possible - letting user know) specific tags of repos in marathon add

### ISSUE THREAD

**Issue by johndpope** [JohnSundell/Marathon#81]
➜  Desktop marathon help add
📦  add
------
Add a package from a given URL to be able to use it from your scripts

👉  Usage: 'marathon add <url-or-path-to-package>'

ℹ️  You can also use a 'Marathonfile' to automatically add packages. See https://github.com/johnsundell/marathon for more information

**Comment by johndpope** [comment]
eg. want to add tag 0.0.1
 marathon add https://github.com/johndpope/swift-grpc-tensorflow.git 

https://github.com/johndpope/swift-grpc-tensorflow/tree/0.0.1

**Comment by JohnSundell** [comment]
Version pinning is not yet supported, but it's something that we do want to add support for. I added this issue: https://github.com/JohnSundell/Marathon/issues/82 to keep track of this new feature, so feel free to put any comments/suggestions you might have in there 🙂 Closing this in favor of the linked issue.
