### ISSUE TITLE
Run SwiftLint in CI

### ISSUE THREAD

**Issue by pixyzehn** [JohnSundell/Marathon#84]
I added [SwiftLint](https://github.com/realm/SwiftLint) to Marathon, but it works only in local so far.
So, this issue is aiming to run SwiftLint in CI to make sure to enforce a good Swift style.

See also https://github.com/JohnSundell/Marathon/pull/61

**Comment by pixyzehn** [comment]
@JohnSundell Could you assign this to me?

**Comment by JohnSundell** [comment]
@pixyzehn Done 👌
