### ISSUE TITLE
Should scripts names maintain user capitalization

### ISSUE THREAD

**Issue by clayellis** [JohnSundell/Marathon#87]
`marathon create SomeScript` produces a target named `Somescript`. Should the default behavior be to capitalize target names while maintaining other capitalized letters? e.g.:

`SomeScript` -> `SomeScript` instead of `Somescript`
`someScript` -> `SomeScript` instead of `Somescript`

What do you think @JohnSundell?

**Comment by JohnSundell** [comment]
@clayellis Sounds like a nice improvement, but I'm not sure if it really matters, given that this is only for the temporary Xcode project. Or am I missing something? 😄

**Comment by clayellis** [comment]
At this point, it's just a nicety really! It would have no effect other than consistency with what the user had entered (since it does end up being a user-facing name anyways.) It would be a one-line fix.

**Comment by garricn** [comment]
It would make `export` slightly easier since the project and file name could be based on `script.name` without modification rather than `arguments[0]` with modificatio, as I'm doing now.

**Comment by JohnSundell** [comment]
Alright, so let's do it 👍

**Comment by JohnSundell** [comment]
Fixed this as part of adding Swift 4 support 🎉 https://github.com/JohnSundell/Marathon/pull/107
