### ISSUE TITLE
Fix create script --no-open not adding script to managed scripts

### ISSUE THREAD

**Issue by garricn** [JohnSundell/Marathon#93]
I noticed an issue where running `marathon create script --no-open` fails to add `script.swift` to managed scripts. Running `marathon list` shows script not listed and checking `scriptManager.managedScriptPaths` returns 0 elements.

Is this a bug?

**Comment by JohnSundell** [comment]
This is not a bug, as Marathon has no reason to start managing a script if the user doesn't want to open it 🙂 The only reason Marathon starts managing a script is to be able to generate a package for it, and this is only needed if it should either be run, installed, or edited using Xcode.

**Comment by garricn** [comment]
Thank you
