### ISSUE TITLE
Marathon edit looking for GitHub repo when it shouldn't

### ISSUE THREAD

**Issue by clayellis** [JohnSundell/Marathon#94]
If you run `marathon edit FooScript` it prints this error:
```
🏃  Cloning https://github.com/FooScript.swift.git...
💥  Failed to download script from 'https://github.com/FooScript.swift.git' (ShellOutError(message: "remote: Not Found\nfatal: repository \'https://github.com/FooScript.swift.git/\' not found", output: ""))
👉  Make sure that the URL is reachable, and that it contains a valid Swift script
```
It seems like Marathon should know that it shouldn't try to resolve scripts from GitHub unless there is a `/` in the path (since you won't ever find any repos directly off of `https://github.com/`, but rather after `username/`. Marathon assumes right away that if the script doesn't exist at that path it must be a remote repo, which might be too hasty of an assumption. 

If you agree @JohnSundell, perhaps we prompt the user that the script doesn't exist and that they can create it using `marathon create FooScript`.

**Comment by JohnSundell** [comment]
Yeah, this is a bug. It's a regression caused by https://github.com/JohnSundell/Marathon/pull/76, will fix it 👍 Will also add the prompt like you suggested @clayellis, great idea! 🚀
